version: '3.9'

services:
  app:
    container_name: app
    build: 
      context: ../..
      dockerfile: ./ops-tools/docker/images/app/Dockerfile
    environment:
      - SPRING_DATASOURSE_URL=jdbc:postgresql://localhost:5432/school
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=school
      - SPRING_JPA_GENERETE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create 
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    networks:
      docker-practice-net:
        ipv4_address: 172.16.238.2
        aliases:
          - app

  postgres:
    container_name: postgres
    image: postgres:11.13-alpine
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=school
    volumes:
       - ../../data/postgres:/var/lib/postgresql/data
       - ../../data/dump:/db_dump
    ports:
      - "5555:5555"
    networks:
      docker-practice-net:
        ipv4_address: 172.16.238.3
        aliases:
          - postgres

  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"
    networks:
      docker-practice-net:
        ipv4_address: 172.16.238.4
        aliases:
          - redis

networks:
  docker-practice-net:
    name: docker-practice-net
